### ISSUE TITLE
app freeze when turning the map

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#104]
**Describe the bug:**
When turning the OSM map when not all tiles are loaded the the app freezes.

**To Reproduce:**
1. from main screen open map
2. turn the mobile to lanscape / portrait

**Actual behavior/state after performing these steps:**
The app freezes.
After some time it is restarted and shows the main screen.

**Expected behavior/state after performing these steps:**
No freeze.

**Version of WhereYouGo used:**
master with PR #93

**Is the problem reproducible:**
Yes

**Additional context:**
~~~
 I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
 W/System.err: java.io.InterruptedIOException: thread interrupted
 W/System.err:     at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
 W/System.err:     at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
 W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
 W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:60)
 W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:466)
 W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:396)
 W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
 W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:726)
 W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:702)
 W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:740)
 W/System.err:     at org.mapsforge.android.maps.mapgenerator.tiledownloader.TileDownloader.executeJob(TileDownloader.java:67)
 W/System.err:     at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:97)
 W/System.err:     at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:141)
 D/skia: ---- read threw an exception
 D/skia: ------ png error Read Error!
 W/MainApplication: onAppMinimized()
 W/PreferenceValues: disableWakeLock(), wl:null
~~~

**Comment by CachingFoX** [comment]
In the past I have the same problem on my old LG G4 device. It didn't depend on the Android version. After updates of Android I had the same problem again and again. By the way I have the same problem with c:geo - but only if I use online maps. 
On my new device the problem never occurs.
