### ISSUE TITLE
Unstoppable loop of crashes 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/WhereYouGo#243]
**Describe the bug:**
It is already some days ago, so unfortunately I don't know any more if/how it was reproducible. But I had to reinstall WhereYouGo completely to get out of this crashing loop... 

**Version of WhereYouGo used:**
2020.08.21

```
FATAL EXCEPTION: MapWorker
Process: menion.android.whereyougo, PID: 24777
java.lang.IllegalArgumentException: invalid longitude: -180.00000000000003
	at org.mapsforge.core.model.CoordinatesUtil.validateLongitude(CoordinatesUtil.java:133)
	at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:85)
	at org.mapsforge.map.reader.MapDatabase.decodeWayNodesSingleDelta(MapDatabase.java:388)
	at org.mapsforge.map.reader.MapDatabase.processWayDataBlock(MapDatabase.java:686)
	at org.mapsforge.map.reader.MapDatabase.processWays(MapDatabase.java:790)
	at org.mapsforge.map.reader.MapDatabase.processBlock(MapDatabase.java:458)
	at org.mapsforge.map.reader.MapDatabase.processBlocks(MapDatabase.java:547)
	at org.mapsforge.map.reader.MapDatabase.readMapData(MapDatabase.java:326)
	at org.mapsforge.android.maps.mapgenerator.databaserenderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:199)
	at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:99)
	at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:141) 
```

**Comment by on4bam** [comment]
Version 2020.08.21

I ran into this yesterday. Hadn't done any Wherigo for a while but the version I had on my Samsung Galaxy Tab S2 (Android 7.0) has all available updates.
Started the app > crash > restart > crash > close. I restarted a few times with the same result even after restarting the tablet.
I uninstalled the app and re-installed. I only changed the Wherigo folder. I could then load the cardridge and start the Wherigo. As the default map would not load I went to the settings tab to change which map to use and it was then the app crashed and again could not be started again.
Back home I uninstalled and re-installed again. I haven't used the app in the field again to see if I get back in the crash loop.
