### ISSUE TITLE
CI does not build WhereYouGo anymore

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#286]
## Bug description

The last two PR build is running of strange errors.
The error is on both executors cgeo-4 and cgeo-5.
One PR targets release, the other master.

### Steps to reproduce the problem
see 
https://ci.cgeo.org/job/whereyougo%20(PR)/464/console
https://ci.cgeo.org/job/whereyougo%20(PR)/465/console

### Actual result after these steps
~~~
15:17:11  FATAL: command execution failed
15:17:11  java.io.IOException: Backing channel 'JNLP4-connect connection from 192.168.0.4/192.168.0.4:34374' is disconnected.
15:17:11  	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:214)
15:17:11  	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
...
~~~
and later
` ERROR: cgeo-4 is offline; cannot locate JDK 1.7 u4 `

@mucek4 Did you changed something between 10.04. and 19.04. ?

**Comment by bekuno** [comment]
cgeo-4 has no such errors anymore.
Cosing here.
