### ISSUE TITLE
NPE in Settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#337]
### Describe your problem!

Reported by Google Play pre-lanuch report for beta phase of 2022.01.02:

```
FATAL EXCEPTION: Thread-8
Process: menion.android.whereyougo, PID: 10265
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.CheckBoxPreference.setEnabled(boolean)' on a null object reference
	at menion.android.whereyougo.gui.fragments.settings.SettingsGlobalFragment.lambda$onCreatePreferences$2$SettingsGlobalFragment(SettingsGlobalFragment.java:61)
	at menion.android.whereyougo.gui.fragments.settings.-$$Lambda$SettingsGlobalFragment$bcK24qnZIOporeAtNnYvdmoeSvM.onPreferenceChange(Unknown Source:2)
	at androidx.preference.Preference.callChangeListener(Preference.java:1118)
	at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference.performClick(Preference.java:1166)
	at androidx.preference.CheckBoxPreference.performClick(CheckBoxPreference.java:90)
	at androidx.preference.Preference$1.onClick(Preference.java:181)
	at android.view.View.performClick(View.java:7869)
	at android.view.View.performClickInternal(View.java:7838)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29362)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

### How to reproduce?

- Open Settings
- Open Global
- Tap on "Run app if screen is off"

### Actual result after these steps?

Crash 

### Expected result after these steps?

Normal operation

### Reproducible

Yes

### WhereYouGo Version

2022.01.02

**Comment by Lineflyer** [comment]
@SchoolGuy Can you take a look? Discovered this crash in the new WhereYouGo settings sadly only recently.
